title: Emma Tong
author: Emma Tong
email: eat2004@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello! My name is Emma Tong and here is a website all about me.
theme: minima

# social links
twitter_username: emma_lily11 # DO NOT include the @ character, or else the build will fail!
github_username:  etong11 # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
